### ISSUE TITLE
Avoid breaking URLs when possible

### ISSUE THREAD

**Issue by smunson** [uwdub/web-dub#18]
The current dub site is pretty well indexed -- both normal Google and Google scholar, with some dub folks using it as their primary profile or primary papers repository and many PDFs hard-linked from other sites around the web. 

If the URL schema changes, we (you?) ideally could 301 Redirect for at least author pages, paper PDFs, and paper pages. (possibly project pages too?)

**Comment by jayfo** [comment]
What pages are currently considered important? Do we have a way of determining that?

Redirecting every page on the existing site seems like a roadblock to launching. The web will adapt and recrawl things. But is there something quick / easy to do here?

**Comment by smunson** [comment]
I think remappingpeople pages for at least a bit is good (if possible).




I think that leaving the PDFs of papers helps (for some papers, the dub site is currently the only non-paywall version).




sean

**Comment by jayfo** [comment]
Generating the 301 is going to require a change in the server itself (i.e., start using a proper server instead of just serving directly from Jekyll). Possible but obnoxious.

1) People content. There's not much of it. Can directly migrate that onto new people pages.

2) Paper pages seem to have no content. Is there an example where that node page has content we need to preserve?

3) Paper PDFs are more difficult to migrate, because they won't naturally be at the same URL. These are URLs you would want set up as a redirect?

**Comment by smunson** [comment]
1) People content. There's not much of it. Can directly migrate that onto new people pages.

On further thought, I am not sure that people links matter as much as I had thought. 


2) Paper pages seem to have no content. Is there an example where that node page has content we need to preserve?

I haven’t seen any.


3) Paper PDFs are more difficult to migrate, because they won't naturally be at the same URL. These are URLs you would want set up as a redirect?

Yes - my understanding was that the site originally is not going to have publications. During that time (if that’s still happening), it would be good for the existing PDF URLs to just be live. Once there is a new pubs directory, redirects would be good — at least long enough for Google Scholar to learn about them, possibly longer unless it causes other problems.

**Comment by jayfo** [comment]
This was easier than I thought. I'll spin a separate issue on people content.

I have taken all of the papers that were hosted on DUB, put them in a container, and set up the proxy to rewrite the URL of the directory they were hosted from. It was a very particular URL, so we are not going to have that URL in the new site, and they can live there for a quite a while.

fogies/slicer-services#20

The old host:
http://dub.washington.edu/djangosite/media/papers/publiccommitments.pdf

The new host:
http://dubstaging.cs.washington.edu/djangosite/media/papers/publiccommitments.pdf

When dubstaging becomes live, those URLs will just work. We could eventually decide we want to 301 them in order to condense their karma or otherwise keep them maximally available, but this seems plenty fine for a launch. Agree?

**Comment by jayfo** [comment]
@smunson 

If you agree that keeping the paper PDFs alive is the critical item here, we can close this issue?

**Comment by smunson** [comment]
Yes



On May 19, 2015 at 10:38:27 PM, James Fogarty (notifications@github.com) wrote:

@smunson

If you agree that keeping the paper PDFs alive is the critical item here, we can close this issue?
